stages:
  - build

cache:
  key: "$CI_JOB_STAGE-$CI_COMMIT_REF_SLUG"
  paths:
    - node_modules
    
.base:
  image: node:lts
  tags:
    - shareRunner

build:
  stage: build
  extends: .base
  script:
    - npm config set registry http://npm.weimob.com
    - npm install
    - npm install weimob-gitlab-ci-tools@latest -g --registry http://npm.weimob.com
    - npm run build
  only:
    - master






