stages:
  - build
  - notify

variables:
  NPM_TOKEN: "XlQ/gB4CvwUgvwRD7A8gva6JmgtrGxYtzd7WB4iNSqI="

cache:
  key: "node_modules"
  paths:
    - node_modules/

.base:
  image: node:lts
  tags:
    - xiaoke-ci

build:
  stage: build
  extends: .base
  script:
    - npm install
    - npm run build
    - npm run semantic-release
  artifacts:
    expire_in: 1 day
    paths:
      - es
  only:
    refs:
      - master
      - beta

succ:
  stage: notify
  extends: .base
  cache: {}
  script:
    - xkc remind
      -s markdown
      -n "${GITLAB_USER_LOGIN}"
      -m "【销氪】<font color="warning">${CI_PROJECT_NAME}</font>执行CI构建成功。\n> 构建分支：<font color="comment">${CI_COMMIT_REF_NAME}</font>\n部署日志：[点击查看](${CI_PIPELINE_URL})"
  when: on_success

fail:
  stage: notify
  extends: .base
  cache: {}
  script:
    - xkc remind
      -s markdown
      -n "${GITLAB_USER_LOGIN}|di.dai"
      -m "【销氪】<font color="warning">${CI_PROJECT_NAME}</font>执行CI构建失败。\n> 构建分支：<font color="comment">${CI_COMMIT_REF_NAME}</font>\n失败流程：<font color="comment">${CI_JOB_STAGE}</font>\n部署日志：[点击查看](${CI_PIPELINE_URL})"
  when: on_failure
